version: '3.4'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
#    depends_on:
#      - database
#      - redis
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/usr/local/bundle/gems
#      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development

volumes:
  gem_cache:
#  node_modules:
